name: OKX K-Line Checker

on:
  # 每小时的14,29,44,59分钟触发
  schedule:
    - cron: '14,29,44,59 * * * *'
  # 允许手动触发
  workflow_dispatch:

jobs:
  check-kline:
    runs-on: ubuntu-latest
    env:
      BARK_KEY: ${{ secrets.BARK_KEY }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pyjwt numpy pandas
          
      - name: Run K-Line Check
        run: |
          python okx_kline_checker.py
